### ISSUE TITLE
Remove FuseBox dependency

### ISSUE THREAD

**Issue by chimon2000** [fuse-box/fuse-react#2]
When using this library outside of FuseBox, I receive errors about FuseBox being undefined.  Is it possible to remove this dependency?

**Comment by nchanged** [comment]
@chimon2000 hi
But fuse-box is in devDeps that wouldn't matter, would it?

**Comment by chimon2000** [comment]
See the following example: https://codesandbox.io/s/70l6z3630

I believe the root cause is here:

https://github.com/fuse-box/fuse-react/blob/0ef53766bd78638ee395d24c6316149becfbe76d/src/Store.tsx#L15-L20

**Comment by nchanged** [comment]
Thanks, that is closed and released!
