### ISSUE TITLE
support for new React lazy

### ISSUE THREAD

**Issue by Zaitsev** [fuse-box/fuse-react#3]
Seems its no compatible with new React lazy loading
https://reactjs.org/blog/2018/10/23/react-v-16-6.html

**Comment by nchanged** [comment]
@Zaitsev Why would you need it be compatible? If you can use just the dynamic `import` statement? 

`<Switch component={() => import("./component")}/>` which is easier.

**Comment by Zaitsev** [comment]
Yes you are right, I just mismatched purposes of this package and react.lazy
