### ISSUE TITLE
Is this maintained anymore?

### ISSUE THREAD

**Issue by erikdao** [fuse-box/fuse-react#5]
Hi,
This looks like a promising alternative to `react-router-dom`, however the latest commit seems to be from 14 months ago. I'm wondering if this repository is still actively being developed cuz I'm considering using `fuse-react` for my project.

Thanks,

**Comment by nchanged** [comment]
@erikdao hi, well, I am not actively maintaining it, but I am using this lib in my personal projects. Feel free to take over if you want ;-) I don't want it to die out.

**Comment by erikdao** [comment]
@nchanged Thanks!
I want to, but I'm afraid I'm not skillful enough in JS, React to make considered contributions. I'll try anyway.
